// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.2
// source: protos/feed.proto

package monster_mutt

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MonsterMutt_FeedLetty_FullMethodName = "/protos.MonsterMutt/FeedLetty"
)

// MonsterMuttClient is the client API for MonsterMutt service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MonsterMuttClient interface {
	FeedLetty(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type monsterMuttClient struct {
	cc grpc.ClientConnInterface
}

func NewMonsterMuttClient(cc grpc.ClientConnInterface) MonsterMuttClient {
	return &monsterMuttClient{cc}
}

func (c *monsterMuttClient) FeedLetty(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, MonsterMutt_FeedLetty_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MonsterMuttServer is the server API for MonsterMutt service.
// All implementations must embed UnimplementedMonsterMuttServer
// for forward compatibility.
type MonsterMuttServer interface {
	FeedLetty(context.Context, *emptypb.Empty) (*emptypb.Empty, error)
	mustEmbedUnimplementedMonsterMuttServer()
}

// UnimplementedMonsterMuttServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMonsterMuttServer struct{}

func (UnimplementedMonsterMuttServer) FeedLetty(context.Context, *emptypb.Empty) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FeedLetty not implemented")
}
func (UnimplementedMonsterMuttServer) mustEmbedUnimplementedMonsterMuttServer() {}
func (UnimplementedMonsterMuttServer) testEmbeddedByValue()                     {}

// UnsafeMonsterMuttServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MonsterMuttServer will
// result in compilation errors.
type UnsafeMonsterMuttServer interface {
	mustEmbedUnimplementedMonsterMuttServer()
}

func RegisterMonsterMuttServer(s grpc.ServiceRegistrar, srv MonsterMuttServer) {
	// If the following call pancis, it indicates UnimplementedMonsterMuttServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MonsterMutt_ServiceDesc, srv)
}

func _MonsterMutt_FeedLetty_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MonsterMuttServer).FeedLetty(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MonsterMutt_FeedLetty_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MonsterMuttServer).FeedLetty(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// MonsterMutt_ServiceDesc is the grpc.ServiceDesc for MonsterMutt service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MonsterMutt_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "protos.MonsterMutt",
	HandlerType: (*MonsterMuttServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "FeedLetty",
			Handler:    _MonsterMutt_FeedLetty_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protos/feed.proto",
}
